apiVersion: v1
kind: Service
metadata:
  name: goserver-service
spec:
  # Responsável por filtrar todos os pods que vão estar incorporados neste serviço
  selector:
    app: goserver-pod-label
  type: LoadBalancer
  ports:
  - name: goserver-portservice
    port: 80 # Porta expõe o service internamente na aplicação
    targetPort: 8000 # Porta da aplicação contida no pod
    protocol: TCP

    